### ISSUE TITLE
Need help with tests

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-bundle#109]
Hi all,

I need some help with improving our test suite. Currently our test suite runs a `serverless` CLI command and checks the output. But these are all run synchronously. This means that you've to wait for all the tests to complete before seeing a result. This is because we are running a `spawnSync`.

``` js
  const { stdout, error } = spawnSync("serverless", cmd || invokeCmd, {
```

It would great if we can run each test and show its output as it completes. Does anybody know how to fix this?

**Comment by carlcheel** [comment]
I don't believe this is because of `spawnSync`. I think it's because all of the tests are in one `index.test.js` file.

Jest runs tests in a file serially and only report the results after all `it/test` blocks have ran.

This example produces the same behaviour:

```

describe("example", () => {
  async function delay(delay) {
    await new Promise((resolve) => {
      setTimeout(() => {
        resolve();
      }, delay);
    });
  }

  it("test 1", async () => {
    await delay(1000);

    expect(true).toBe(true);
  });

  it("test 2", async () => {
    await delay(2000);

    expect(true).toBe(true);
  });

  it("test 3", async () => {
    await delay(3000);

    expect(true).toBe(true);
  });
});
```

If we provide a test file per feature, that would fix the issue. It would then make use of jest parallelization which will improve the performance of the tests too.

**Comment by carlcheel** [comment]
Hey @jayair managed to find some time to look at improving the test suite. Opened a PR.

**Comment by jayair** [comment]
Thank you for helping fix it!
