### ISSUE TITLE
Option to mark all node_modules as externals

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-bundle#145]
Referring to this issue (https://github.com/AnomalyInnovations/serverless-nodejs-starter/issues/61) created by @OBrown92.

There are some cases (like when using `ejs`) when you need to explicitly exclude pretty much all packages.

**Comment by jayair** [comment]
@OBrown92 I added an `all` option to the `externals`. This automatically ignores all the packages in your node_mdoules. So you won't have to list each one. I tried it with your sample repo and it worked — https://github.com/OBrown92/serverless-email-templates.

Here's how you can test it.

Install the test version.

``` bash
$ npm install --save-dev AnomalyInnovations/serverless-bundle#issue-145-nodeexternals
```

And set this in your `serverless.yml`.

``` yml
custom:
  bundle:
    externals: all
```

Give it a try and let me know and we'll merge it master.

**Comment by jadczakd** [comment]
Wouldn't it be good to add it to the forceExclude as well? For projects where you're using common layers for all the modules?
Ideally I would like the bundler to take in just the internal package modules, and nothing from the global modules path.

**Comment by jayair** [comment]
That's interesting. Do you have cases where all your packages are supplied by Lambda layers?

**Comment by jayair** [comment]
Merged and released this: https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v3.2.0

**Comment by jadczakd** [comment]
> That's interesting. Do you have cases where all your packages are supplied by Lambda layers?

Yeah, when I build something with a common codebase I do that. Not only for npm packages but also with some inner libraries - wg when I bundle anything containing Dialogflow , the bundle size grows to ~3 Mb per function. With aws-sdk its not so bad as it goes to roughly 50 KB , but to think of it when You have something really simple and write it through the console the lambda is actually just a couple of bytes.

I don't mind the smaller sizes much, but the 3 mb of dialogflow actually causes a timeout because of how much longer the startup + parsing takes.

**Comment by jayair** [comment]
On the flip side, if everything is excluded, then whats the point of using Webpack?

**Comment by jadczakd** [comment]
Just an easy way to do stage 0 and newer syntax admittedly, it's not always that I do it , I am happy with excluding the way I can do it now. This would just be a handy helper.
