### ISSUE TITLE
WARNING: More than one matching handlers found for...

### ISSUE THREAD

**Issue by RandomEngy** [AnomalyInnovations/serverless-bundle#189]
I'm getting this warning when deploying:

WARNING: More than one matching handlers found for 'built/methods/registerDevice'. Using 'built/methods/registerDevice.js'.

I'm guessing this is because Typescript has included registerDevice.js and registerDevice.js.map.

serverless-webpack added a [feature to exclude files via config](https://github.com/serverless-heaven/serverless-webpack/pull/471), but I cannot use this, as custom/bundle and custom/webpack config sections are not compatible.

How do I get rid of this warning?

**Comment by karl-run** [comment]
I'm also seeing this warning because I have `handler.ts` and `handler.test.ts`. Same as [this issue](https://github.com/serverless-heaven/serverless-webpack/issues/405) in `serverless-webpack`. Which lead to [this feature request](https://github.com/serverless-heaven/serverless-webpack/issues/433) which in turn lead to the PR linked in OPs issue.

Being able to do something like this:
```
custom:
  bundle:
    excludeFiles: '**/*.test.ts'
```

Would be nice.

**Comment by jayair** [comment]
Closed in https://github.com/AnomalyInnovations/serverless-bundle/pull/245

**Comment by RandomEngy** [comment]
Thanks, this is handy, but I Typescript generates `.d.ts` files for type information as well as `.map` source maps. I would need access to the `excludeRegex` option from serverless-webpack to make this work. But currently it's being hard-coded to `/bundle_stats\.(html|json)$/`
