### ISSUE TITLE
Allow serverless-webpack configuration options to pass through

### ISSUE THREAD

**Issue by phobetron** [AnomalyInnovations/serverless-bundle#71]
Currently, I need to set `keepOutputDirectory: true` for `serverless-webpack`, but I can't. There should be a way to pass valid options through to `serverless-webpack` instead of shaming people for needing more than the defaults.

**Comment by david-l-riley** [comment]
Seconded. It's good to have a nice set of defaults that work for most people, but refusing to expose the knobs for controlling things where the default won't suffice is incredibly frustrating.

**Comment by MarcWadai** [comment]
+1

**Comment by jayair** [comment]
While we are definitely trending in the direction of adding most of the Webpack options, I'm not sure what's giving the impression that we are refusing to expose all the options?

That said `keepOutputDirectory` is something we should add. I'm happy to accept PRs for this.

While we are on the subject, what other serverless-webpack options do we have left? Aside from the `webpackConfig` option; since altering that invalidates the purpose of this plugin.

**Comment by david-l-riley** [comment]
That impression comes from the copy in README.md:

```
This plugin does not support customizing the Babel and Webpack configs, since serverless-webpack does a pretty good job with that.
```

But the problem is that if you want to do something outside of what's explicitly exposed, you have to go and edit the source to add it to the webpack config (I suppose it could also be done with scripts, but that seems kinda gross).

I don't think adding an option to overlay custom options would be really invalidating the purpose of the plugin. I think it does a great job setting default options! But there needs to be a way to inject/overlay custom options to the webpack config (not just custom options to `serverless-webpack`), or things like aliasing modules to quiet webpack warnings can't be done. I suspect just loading an overlay file and doing an `Object.assign()` would do the trick, though I haven't tested that; perhaps a PR would be the way to go here?

Apologies if that came across as combative, that's not my intent; I think you've done a great job of really simplifying the process of building a usable Webpack serverless module (especially when it comes to including static assets, which is why I tried it out in the first place). Thank you for your hard and probably often thankless work on this very useful plugin.

**Comment by jeff-kilbride** [comment]
Agreed. While `serverless-webpack` does do a good job, they also recognized the need for customization of the underlying config:

https://github.com/serverless-heaven/serverless-webpack#full-customization-for-experts

The `serverless-bundle` package is a great idea and makes setting things up very easy -- and I appreciate that. I just think the `create-react-app` model of restricting access to various configs is too limiting.

**Comment by MarcWadai** [comment]
Yes, your work on the package is amazing, and save lot of time for developer. But when some minor changes needs to be done, it is very frustrating to not be able :/ 
Concrete example, I got problem from webpack not being able to read properly module.exports (trying to convert everything into import/exports ES6 format). And could have solve it easily by adding some conf to the babel package.. which is not possible with serverless-bundle

**Comment by jayair** [comment]
Thanks for the feedback all. I'll add this to the README after but we want to do a couple of things for customization cases like this:

- If there is a common need, we want to build it into the plugin. This helps because we don't want to start having people managing these overriding configs. It also means that you can simply include the plugin and it would work out of the box for majority of cases.
- For cases where there is no way to build it into the plugin, we'll add an option. We want to make sure we design the options well, so that it's easy for people to understand. The biggest reason for all of this is that Webpack is incredibly complex for most people to configure. We want to ensure that we are helping people with that. We've also noticed that in a lot of cases where people think they need an additional option, and it turns out it's already supported another way.

So we want it to work well for most cases out of the box, and have options to handle the rest. To do this, we like to look at the issues case by case. It does take time but the efforts are well worth it. And we could use your help to handle the specific issues.

Please create a separate thread for the issue you are having and we'll try fix it.

**Comment by s1mrankaur** [comment]
@jayair  Need     keepOutputDirectory: true .

I have set everything up in the project and using the serverless bundle. Now need to keep .webpack directory to debug lambda functions using thundra and it keeps getting deleted. Please suggest a way to do it.

**Comment by s1mrankaur** [comment]
@phobetron  How did you do it?

**Comment by s1mrankaur** [comment]
+1

**Comment by webjunkie** [comment]
If you look at https://github.com/AnomalyInnovations/serverless-bundle/blob/master/index.js#L39 you will see that `keepOutputDirectory` is set by `generateStatsFiles`. Might that help?
