### ISSUE TITLE
how can I bundle the package 'isomorphic-webcrypto'?

### ISSUE THREAD

**Issue by tomeraz** [AnomalyInnovations/serverless-bundle#99]
I'm importing SigV4RequestSigner from npm package [amazon-kinesis-video-streams-webrtc](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js)
Getting the following error on build:
```
ERROR in .../node_modules/isomorphic-webcrypto/src/index.mjs 2:19-25
Can't import the named export 'Crypto' from non EcmaScript module (only default export is available)
 @ .../node_modules/amazon-kinesis-video-streams-webrtc/lib/SigV4RequestSigner.js
 @ .../node_modules/amazon-kinesis-video-streams-webrtc/lib/index.js
 @ .../createStreamingChannel.js
```

Looks like in order for webpack to bundle properly webpack config needs to contain:
```
    externals: {
        'isomorphic-webcrypto': 'crypto',
    },
```

as shown in this [webpack config](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/webpack.config.js).

Is there any way to adjust serverless-bundle configuration to enable this build?

**Comment by jayair** [comment]
We just added support for extended the `externals` option https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v1.7.0. Not sure if that fixes it for you?

**Comment by tomeraz** [comment]
@jayair I'm pretty new to lambda. Using serverless-stack to setup my own app.
So you're suggesting I can define 'isomorphic-webcrypto' as an external and then load it through a lambda layer to avoid building it with serverless-bundle?

**Comment by tomeraz** [comment]
I was able to load the entire library that was using this lib as a layer and using the new externals feature.
Thanks!

**Comment by jayair** [comment]
@tomeraz Just a heads up, there was an issue with the `externals` option that was causing it to be excluded from the package. This worked for your use case but it breaks for others — https://github.com/AnomalyInnovations/serverless-bundle/issues/103.

To fix this we added a new `forceExclude` option for packages that are available in the Lambda runtime by default or through a Layer. You can read more about it here — https://github.com/AnomalyInnovations/serverless-bundle#externals-vs-forceexclude.

https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v1.8.0

So you'll need to use the `forceExclude` option instead of the `externals` option.
